[project]
name = "carla-rl"
version = "0.1.0"
description = "CARLA reinforcement learning"
requires-python = ">=3.8"
dependencies = [
    "setuptools",
    "numpy>=1.21.0",
    "opencv-python>=4.5.0",
    "tqdm>=4.0.0",
    "torch>=1.9.0",
    "torchvision>=0.10.0",
    "tensorboard>=2.14.0",
]
